// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClearService 暴露给前端的目录清理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * DeleteDirs 异步批量删除目录，每个目录删除完成后通过 scanEvent 推送
 */
export function DeleteDirs(dirs: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(1615123099, dirs);
}

/**
 * GetDisks 返回当前可用的磁盘列表（Windows），其他平台返回根目录
 */
export function GetDisks(): $CancellablePromise<string[] | null> {
    return $Call.ByID(271702230);
}

/**
 * StartScan 异步扫描指定目录，扫中的目录通过 scanEvent 逐个推送给前端
 */
export function StartScan(dir: string): $CancellablePromise<string> {
    return $Call.ByID(1448624653, dir);
}
