// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScanEvent 扫描/删除进度事件（替代原websocket推送的消息结构）
 */
export interface ScanEvent {
    "type": string;
    "data": string;
}
